package com.java.string.examples;

import java.util.Iterator;
import java.util.SplittableRandom;
import java.util.StringTokenizer;

import org.apache.commons.lang3.StringUtils;

import com.google.common.base.Splitter;

public class StringSplit {

	public static void main(String[] args) {
		  /*
		  Java String class defines following methods to split Java String object.
		  String[] split( String regularExpression )
		  Splits the string according to given regular expression.
		  String[] split( String reularExpression, int limit )
		  Splits the string according to given regular expression. The number of resultant
		  substrings by splitting the string is controlled by limit argument.
		  */
		 
		  /* String to split. */

		String str1 ="Hello Java World";
		
		String[] arrStr1;
		
		/*delimiter*/
		
		String delimiter=" ";
		
		arrStr1 = str1.split(delimiter);
		
		for (int i = 0; i < arrStr1.length; i++) {
			System.out.println(arrStr1[i]);
		}
		
		
		  /*
		  Using second argument in the String.split() method, we can control the maximum
		  number of substrings generated by splitting a string.
		  */
		
		
		arrStr1 = str1.split(delimiter, 3);
		for (int i = 0; i < arrStr1.length; i++) {
			System.out.println(arrStr1[i]);
		}
		
		
		
		//Using String tokenizer 
		
		//Method 1 using StringTokenizer
		
		String str2 = "I am a simple string and will be tokenized on space";
		StringTokenizer tokenizer = new StringTokenizer(str2);
		
		while (tokenizer.hasMoreTokens()) {
			System.out.println(tokenizer.nextToken());
		}
		
		//Method 2 using StringTokenizer - with multiple tokens
		
		String str3 = "http://howtodoinjava.com/java-initerview-questions";
		
		StringTokenizer tokenizer2 = new StringTokenizer(str3, "://.-");
		while (tokenizer2.hasMoreTokens()) {
			System.out.println(tokenizer2.nextToken());
		}
		
	
		
	//Using	 String.split() method
		
		String[] tokens = "I,am,a,programming,langauge,whose this ? ".split(","); 
		
		for (String string : tokens) {
			System.out.println(string);	
		}
		
		
		//Method 3 using StringUtils.split()
		
		
		String[] tokens2 = StringUtils.split("I,am ,Legend, , oh ,you ?",",");

		for (String string : tokens2) {
			System.out.println(string);	
		}
		
		
		
		//Method 4 Guava Splitter
		
		Splitter sp =Splitter.on(",").omitEmptyStrings().trimResults();
		
		Iterable<String> tokens3 = sp.split("I,am ,Legend, , oh ,you ?");
		
		for (String string : tokens3) {
			System.out.println(string);
		}
	}
	
	
	
}
